from .funcionarios import Funcionarios
from .tipocontrato import TipoContrato
from .colegios import Colegios
from .financiamiento import Financiamiento
from .alcaldia import Alcaldia
from .jefatura_daem import JefaturaDAEM
from .cargo import Cargo
from .ordenes_trabajo import OrdenesTrabajo
from .usuarios import Usuario
from .roles import Rol
from .permisos import Permiso
from .historial_cambios import HistorialCambios
